spring.application.name=pm
server.port=8081

# ML API Configuration
ml.api.url=http://localhost:8000/predict

# Telemetry Window Configuration
telemetry.window.size=30

# ML Default Vehicle Configuration
ml.defaults.vehicle-type=Truck
ml.defaults.make-and-model=AshokLeyland_1616
ml.defaults.usage-hours=5200
ml.defaults.battery-status=Good
ml.defaults.brake-condition=Fair
ml.defaults.oil-quality=Good
ml.defaults.load-capacity=16
ml.defaults.year-of-manufacture=2019
